source:
  type: "dbt"
  config:
    # Coordinates
    # To use this as-is, set the environment variable DBT_PROJECT_ROOT to the root folder of your dbt project
    manifest_path: "/home/${USER}/SOMA-B2B-SaaS/target/manifest.json"
    catalog_path: "/home/${USER}/SOMA-B2B-SaaS/target/catalog.json"
    run_results_paths:
      - "/home/${USER}/SOMA-B2B-SaaS/target/run_results.json" # optional for recording dbt test results after running dbt test

    # Options
    target_platform: "duckdb" # e.g. bigquery/postgres/etc.

sink:
  # DataHub GMS API 서버 정보
  type: "datahub-rest"
  config:
    server: "http://localhost:8080"