version: 2

soma_b2b_saas:
  target: dev
  outputs:
    dev:
      schema: main
      type: clickhouse
      host: 127.0.0.1
      port: 8123
      user: clickhouse
      password: clickhouse
      dbname: main
