version: 2

soma_b2b_saas:
  target: dev
  outputs:
    dev:
      path: /home/pseudo.dwlee/SOMA-B2B-SaaS/soma_b2b_saas.duckdb
      schema: main
      type: duckdb
      threads: 4
      extensions:
        - httpfs
        - parquet
